version: '3.8'
services:
  client:
    container_name: "prolog-client"
    build: prolog-client/.
    ports:
      - "3000:3000"
    stdin_open: true
    volumes:
      - "./prolog-client:/app"
      - "/app/node_modules"
    environment:
      - CHOKIDAR_USEPOLLING=true
  prolog_server:
    container_name: "prolog-server"
    build: prolog-server/.
    stdin_open: true
    ports:
        - "8080:8080"
  python_server:
    container_name: "python-server"
    build: python-server/.
    stdin_open: true
    ports:
        - "5000:5000"